config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "投稿が成功しました"
    redirect_to book_path(@book.id)

    else
      render :new
    end
  end

  def index
    @books = Book.all
    @book =Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end

  def destroy
    book = book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


 private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Edit", edit_book_path(@book)%>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
    <th>title</th>
      <th>body</th>
    </tr>
  </thead>

   <tbody>

<% @books.each do |book| %>
    <tr>
    <td>
    <%= book.title %>
    </td>

    <td>
    <%= book.body %>
    </td>



  <td>
    <%= link_to "Show", book_path(book.id) %>
  </td>

  <td>
    <%= link_to "Edit", edit_book_path(book.id) %>
   </td>

  <td>
    <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
   </td>
    </tr>

  <% end %>
</tbody>
  </table>




  <h1>New books</h1>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create book' %>



<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
<div>

<h2>Title</h2>
<p><%=@book.title %></p>

<h2>Body</h2>
<p><%=@book.body %></p>

<%= link_to "Edit", edit_book_path(@book)%>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookersへ！</h1>
<p><strong>bookers</strong>では、様々な書籍に関するあなたの意見や<br>
印象を共有し、交換する事が出来ます。</p>



<p><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    
    
    <main>
    <%= yield %>
     </main>
  </body>
</html>